INSERT INTO `vita`.`activity` (`image_url`, `title`, `subtitle`, `content`, `booking_index`, `match_percent`, `lat`, `lng`, `region_id`, `activity_id`, `kind_idkind`, `description`) VALUES ('images/explore_bg.png', 'Loquita', 'Santa Barbara', 'Authentic Spanish food', '3', 100, 34.41421031876199, -119.69164738460584, null, null, null, 'Authentic Spanish food including hot and cold tapas, wood-fired grilled seafood and meats, and seasonal paella.');

INSERT INTO `vita`.`activity` (`image_url`, `title`, `subtitle`, `content`, `booking_index`, `match_percent`, `lat`, `lng`, `region_id`, `activity_id`, `kind_idkind`, `description`) VALUES ('images/photos/brasil_arts_cafe.jpeg', 'Brasil Arts Cafe', 'Santa Barbara', 'Traditional Brazilian fare', '4', 97, 34.42427273044929, -119.70538318430323, null, null, null, 'The perfect blend of traditional Brazilian fare & one-of-a-kind Açai, Juice, and Smoothie creations.');

INSERT INTO `vita`.`activity` (`image_url`, `title`, `subtitle`, `content`, `booking_index`, `match_percent`, `lat`, `lng`, `region_id`, `activity_id`, `kind_idkind`, `description`) VALUES ('images/photos/yoichis.jpg', 'Yoichi''s', 'Santa Barbara', 'Sushi in an intimate setting', '4', 95, 34.42715715496026, -119.70249364197355, null, null, null, 'A prix fixe only spot featuring traditional Japanese small plates &amp; sushi in an intimate setting.');

INSERT INTO `vita`.`activity` (`image_url`, `title`, `subtitle`, `content`, `booking_index`, `match_percent`, `lat`, `lng`, `region_id`, `activity_id`, `kind_idkind`, `description`) VALUES ('images/photos/los_agaves.jpg', 'Los Agaves', 'Santa Barbara', 'Flavors of Mexico', '4', 90, 34.4375036989364, -119.72734258675358, null, null, null, 'The bold flavors of Mexico, an authentic dining experience, high-quality ingredients.');

INSERT INTO `vita`.`activity` (`image_url`, `title`, `subtitle`, `content`, `booking_index`, `match_percent`, `lat`, `lng`, `region_id`, `activity_id`, `kind_idkind`, `description`) VALUES ('images/photos/santo_mezcal.jpg', 'Santo Mezcal', 'Santa Barbara', 'Modern Mexican cuisine', '4', 90, 34.4134427932841, -119.69127914319921, null, null, null, 'Modern Mexican cuisine');

INSERT INTO `vita`.`activity` (`image_url`, `title`, `subtitle`, `content`, `booking_index`, `match_percent`, `lat`, `lng`, `region_id`, `activity_id`, `kind_idkind`, `description`) VALUES ('images/photos/la_super-rica_taqueria.jpg', 'La Super-Rica Taqueria', 'Santa Barbara', 'Celebrated Mexican spot', '4', 90, 34.42790056991083, -119.68722191681411, null, null, null, 'Celebrated Mexican spot for fish tacos, tamales & more served up in modest digs with patio seating.');

INSERT INTO `vita`.`activity` (`image_url`, `title`, `subtitle`, `content`, `booking_index`, `match_percent`, `lat`, `lng`, `region_id`, `activity_id`, `kind_idkind`, `description`) VALUES ('images/photos/constantia.jpg', 'Bridlewood Estate', 'Santa Barbara', 'Guided experience led by Hans Thorvald.', '4', 85, 0, 0, null, null, null, 'The Constantia Valley has an appeal that offers something of interest to everyone, from award winning restaurants offering, luxurious boutique hotel accommodation with spa’s as well as quaint B&B’s. There are beautiful greenbelts to walk on, shops to explore, a brilliant zip lining adventure, mountain biking, horse riding, unique shops and a wine farms.');

INSERT INTO `vita`.`activity` (`image_url`, `title`, `subtitle`, `content`, `booking_index`, `match_percent`, `lat`, `lng`, `region_id`, `activity_id`, `kind_idkind`, `description`) VALUES ('images/photos/hanna-levin.png', 'Hanna Levin &#128994;', 'New Taste Match to Follow!', '23 Similar Tastes <a href=''>View All</a>', '-1', 97, 0, 0, null, null, null, 'A trusted Local Guide.');

INSERT INTO `vita`.`activity` (`image_url`, `title`, `subtitle`, `content`, `booking_index`, `match_percent`, `lat`, `lng`, `region_id`, `activity_id`, `kind_idkind`, `description`) VALUES ('images/photos/cannon-beach.jpg', 'Haystack Rock', 'Cannon Beach, Oregon', 'This is an iconic photo opportunity', '-1', 85, 45.884161669751066, -123.96863053734513, null, null, null, 'This is the Oregon coast''s most iconic photo opportunity.');

INSERT INTO `vita`.`activity` (`image_url`, `title`, `subtitle`, `content`, `booking_index`, `match_percent`, `lat`, `lng`, `region_id`, `activity_id`, `kind_idkind`, `description`) VALUES ('images/photos/rogue_astoria.jpg', 'Rogue Brewery', 'Astoria Oregon', 'Beer tasting experience', '4', 85, 46.196750395147454, -123.79762603067174, null, null, null, 'A popular local brewery with amazing views.');

INSERT INTO `vita`.`activity` (`image_url`, `title`, `subtitle`, `content`, `booking_index`, `match_percent`, `lat`, `lng`, `region_id`, `activity_id`, `kind_idkind`, `description`) VALUES ('images/photos/camel_valley_wines.jpg', 'Stolpman Vineyard', 'Santa Barbara', 'Wine tasting and horse back riding tour', '4', 85, 34.64230332164125, -120.43610020209037, null, null, null, 'A pleasant wine tasting and horse back riding tour.');

INSERT INTO `vita`.`activity` (`image_url`, `title`, `subtitle`, `content`, `booking_index`, `match_percent`, `lat`, `lng`, `region_id`, `activity_id`, `kind_idkind`, `description`) VALUES ('images/photos/gargiulo_vineyards.jpg', 'Rusack Winery', 'Napa Valley Solvang', 'Make your own wine experience', '4', 85, 34.638058462065956, -120.14186578859605, null, null, null, 'Here you can experience making your own wine.');

INSERT INTO `vita`.`activity` (`image_url`, `title`, `subtitle`, `content`, `booking_index`, `match_percent`, `lat`, `lng`, `region_id`, `activity_id`, `kind_idkind`, `description`) VALUES ('images/photos/sunstone_winery.jpg', 'Sunstone Wine Tour with a Local', 'Santa Ynez', 'A true family-run winery', '4', 85, 34.58679315470256, -120.10337263941516, null, null, null, 'Sunstone Wine Tour with a Local');

INSERT INTO `vita`.`activity` (`image_url`, `title`, `subtitle`, `content`, `booking_index`, `match_percent`, `lat`, `lng`, `region_id`, `activity_id`, `kind_idkind`, `description`) VALUES ('images/photos/foxen_vineyard.jpg', 'Foxen Vineyard Wine Tasting Tour', 'Santa Maria', 'Minimalist winemaking', '4', 85, 34.82021411953863, -120.23023950022402, null, null, null, 'Discover minimalist winemaking.');
